const projectsData = [
  {
    key: 9,
    name: 'Stacy',
    link: 'https://github.com/piroBeastie/Stacy-VoiceReceptionist',
    year: 2026,
    image: '',
    description: 'AI phone receptionist for small businesses. Picks up every call, books appointments, replies in 0.95s.',
  },
  {
    key: 0,
    name: 'Asendia',
    link: 'https://asendia.onrender.com/',
    year: 2026,
    image: '/projects/asendia.png',
    description: 'Real-time AI voice interviewer for ML roles.',
  },
  {
    key: 1,
    name: 'Nile',
    link: 'https://nile-theta.vercel.app',
    year: 2026,
    image: '/projects/nile.png',
    description: 'E-commerce web app, MERN stack.',
  },
  {
    key: 2,
    name: 'PersonaAI',
    link: 'https://persona-ai-zeta.vercel.app/',
    year: 2026,
    image: '/projects/personaai.png',
    description: 'Gemini chat with switchable personas.',
  },
  {
    key: 3,
    name: 'LegalSarthi',
    link: 'https://legal-sarthi.vercel.app/',
    year: 2026,
    image: '/projects/legalsarthi.png',
    description: 'AI chatbot that suggests your best legal next step.',
  },
  {
    key: 4,
    name: 'NewsGenius',
    link: 'https://newgenius-frontend.vercel.app/',
    year: 2025,
    image: '/projects/newsgenius.png',
    description: 'News aggregator, React + Python.',
  },
  {
    key: 5,
    name: 'Planet Dist',
    link: 'https://pirobeastie.github.io/Planet-Distance/',
    year: 2024,
    image: '/projects/planetdist.png',
    description: 'Planet distances visualizer, API learning project.',
  },
  {
    key: 6,
    name: 'Spotify C',
    link: 'https://boisterous-mermaid-5baa81.netlify.app/',
    year: 2025,
    image: '/projects/spotifyc.png',
    description: 'Spotify clone.',
  },
  {
    key: 7,
    name: 'Book Store',
    link: 'https://pirobeastie.github.io/Book_Recommendation/',
    year: 2024,
    image: '/projects/bookstore.png',
    description: 'Book recommendation app.',
  },
  {
    key: 8,
    name: 'Retro CSS',
    link: 'https://retro-theme-css.vercel.app/',
    year: 2024,
    image: '/projects/retrocss.png',
    description: 'Retro-themed CSS experiment.',
  },
]

export default projectsData
